name = "SparseGrids"
uuid = "bafbe729-afc6-5148-bb4f-226bf3d46895"
authors = ["Robert DJ <git@dahl-jacobsen.dk>"]
version = "2.0.3"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.5"
FastGaussQuadrature = "1.0"
IterTools = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
